### PR TITLE
Refactor Docs to CI

### PR DESCRIPTION
**Pull request by ilaffey2**
Changed files: 
`docs/` has been removed
`README` now indicates location of new developer docs
BEFORE APPROVING:
How do we want to indicate the current Hulse docs (which are really tutorials) as being different from the python docs? Or integrate the two together.
https://readthedocs.org/projects/hulse-py/builds/17033201/

### CODE REVIEW

**Comment by ilaffey2** [comment]
https://github.com/readthedocs/readthedocs.org/issues/4065 
See here:
Think you may have to set something up @sachalevy 
It is very straightforward, but when I try to "re-sync" webhook I get an error.
If you create an account on readthedocs, I can add you there and it should allow you to instantly grant the correct access.
I can see that webhooks are going through, they just aren't syncing properly/causing a build.
https://readthedocs.org/dashboard/hulse-py/integrations/202035/
I can also see that I can import (and properly setup) integrations for the Mcgill Robotics org, so maybe there is something we are missing, but I think the above fix should work for now. Super simple/

**Comment by sachalevy** [comment]
Ok, we can just let these docs be the default, and I'll port the content from the tutorials' docs to this one (for the dev side of things), and write something either in a blog post or put it on the website for the more demo-ish aspect of the current docs.

My readthedocs username is `sachalevy` - do I need to setup anything else on that end?

**Comment by ilaffey2** [comment]
No! The webhook is now running!!

**Review by sachalevy — APPROVED** [review]

**Comment by sachalevy** [comment]
Looks good to me!

**Comment by ilaffey2** [comment]
This merge successfully activated the webhook :D 
https://readthedocs.org/projects/hulse-py/builds/17033418/

**Comment by sachalevy** [comment]
Great, I'm wondering if there is a way we can add a feature to automatically discover the docstrings? Sphinx has a feature called apidoc which finds docstrings structured a certain way and builds the docs automatically. I'll check if we can add this through readthedocs. also could you add me to the readthedocs project?

**Comment by ilaffey2** [comment]
Yea I will add you there! I have to set that up actually! I was careless and the docs haven't actually generated yet :O, the generated documentation doesn't pickup the doc-strings. Fixing now

**Pull request merged**
