### PR TITLE
Automatically publish releases to PyPi

### PR DESCRIPTION
**Pull request by ilaffey2**
This can be done completely with boilerplate!
All that's needed is to update secrets to contain the api key, and use  `__token__` for username.

More info:
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
https://pypi.org/help/#apitoken

### CODE REVIEW

**Comment by sachalevy** [comment]
I've added the `PYPI_API_TOKEN` secret to the repo, so this should be good.

**Review by sachalevy — APPROVED** [review]

**Comment by ilaffey2** [comment]
Wondering how we test this after merging?
Maybe I will add  #6  and #4  things next, then we can try and see if publishing that as 0.0.1 updates on PyPi automatically?

**Comment by sachalevy** [comment]
Yep I assume that's how we check if it works?
Also, we can integrate this in the CI to automatically make the gh release: https://github.com/marketplace/actions/gh-release.

**Comment by ilaffey2** [comment]
Awesome! Do we want that now? Like a nightly release? Or is just manually deciding when to release alright for now? I honestly feel like since it's still in beta it makes sense to not even worry about nightly/automated releases and just release in batches as we add groups of features.

Totally your call! If so I will add and do in one PR, otherwise we can do this in the future if manually releasing is annoying (it takes very little time)

**Comment by sachalevy** [comment]
You're right, we can leave automating releases for later - this looks good to me, I'll merge!

**Pull request merged**
